- import_tasks: "{{ role_path }}/tasks/hackthebox.yml"
  tags:
    - setup-all
    - setup-theme
    - setup-theme-user

- import_tasks: "{{ role_path }}/tasks/user.yml"
  tags:
    - setup-all
    - setup-theme-user
