---
- name: "Set up pwnbox hosts"
  hosts: "{{ target if target is defined else 'pwnbox_hosts' }}"
  become: true

  roles:
    - pwnbox-packages
    - pwnbox-theme
    - pwnbox-misctools
    - pwnbox-theme
    - pwnbox-system
